### ISSUE TITLE
getValidScale 函数部分场景会遇到浮点数精度问题

### ISSUE THREAD

**Issue by andywang646691** [leaferjs/leafer-ui#291]
如下代码没有考虑浮点数精度问题， 可能会导致反复触发渲染

```ts
leafer.getValidScale = function (changeScale: number): number {
    const { scaleX } = this.zoomLayer.__, { min, max, disabled } = this.app.config.zoom, absScale = Math.abs(scaleX * changeScale)
    if (absScale < min) changeScale = min / scaleX
    else if (absScale > max) changeScale = max / scaleX
    return disabled ? 1 : changeScale
}
```

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the getValidScale method to address floating point precision problems that could cause repeated rendering. Added a small epsilon value to prevent exact comparisons and potential oscillations due to floating point inaccuracies.

You can review changes in this commit: https://github.com/zxsa89675/leaferjs-leafer-ui-291/commit/cf9d8c65a6e82b36acbcb25e0be7f196c88044bc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by leaferjs** [comment]
感谢反馈～
